import { useEffect, useState } from "react";
import useCurrency from './hooks/useCurrency';
import Header from './components/Header';
import CurrencySelect from './components/CurrencySelect';
import AmountInput from './components/AmountInput';
import Result from './components/Result';
import Loader from './components/Loader';

export default function App() {
    
    const [amount, setAmount] = useState(1);
    const [fromCur, setFromCur] = useState("USD");
    const [toCur, setToCur] = useState("INR");
    
   const { converted, isLoading } = useCurrency(amount, fromCur, toCur);
    
        
  return (
      <>
    <main className="app">
      <div className="converter-card">
      
      { isLoading && <Loader /> }
      
        <Header />

        <div className="converter-form">
          <AmountInput amount={amount} setAmount={setAmount}  />

          <div className="currency-row">
            <CurrencySelect currency={fromCur} setCurrency={setFromCur} />

            <span className="arrow">→</span>

            <CurrencySelect currency={toCur} setCurrency={setToCur} />
          </div>

          <Result amount={converted} />
      
        </div>
      </div>
    </main>
      <footer className="footer">This loader is generated by loading.io</footer>
      </>
  );
}






